all:
  vars:
    # Here we use docker to simulate a cloud VPC.
    ansible_connection: docker # usually this would be ssh
    ansible_user: root
    ansible_become: true

atlanta:
  hosts:
    host1.test.confluent:

boston:
  hosts:
    host2.test.confluent: